### ISSUE TITLE
Turn on snippetgen by default

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#1043]
CC @dizcology

There's a small chance snippetgen falls apart on a real API, so I plan to take the following steps to avoid blocking other updates:

- Merge the open release PR: #1037 
- Turn on snippetgen
- Release the new release PR

**Comment by busunkim96** [comment]
There appears to be a bug for client streaming so I wasn't able to enable this globally:

If it takes a while to fix I will back out #1044 so it doesn't block other changes.

```py
    sample["request"] = v.validate_and_transform_request(
  File "/usr/local/google/home/busunkim/.cache/bazel/_bazel_busunkim/5f7ad274936c83fa5125630e373edd54/sandbox/linux-sandbox/1362/execroot/com_google_googleapis/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/samplegen/samplegen.py", line 560, in validate_and_transform_request
    raise types.InvalidRequestSetup(
gapic.samplegen_utils.types.InvalidRequestSetup: Too many base parameters for client side streaming form
--python_gapic_out: protoc-gen-python_gapic: Plugin failed with status code 1.
Target //google/firestore/v1:firestore-v1-py failed to build
```

**Comment by busunkim96** [comment]
Aand I've found at least one other bug - it was not caught by the goldens but was discovered when I tried to use #1077 as the generator version in the WORKSPACE file. I think it is related to https://github.com/googleapis/google-auth-library-python/pull/701. 

I'm planning on manually generating locally with 0.56.1 with every API to shake out remaining bugs blocking turning on snippetgen by default.

**Comment by busunkim96** [comment]
#1012 started to use the resource path logic which wasn't written to handle nested sub-fields. The generation was failing as matching resource paths were not found for resource paths that are not on the base request.

**Comment by busunkim96** [comment]
I've opened #1144 to track re-adding f-string support for resource paths (it requires addressing the bug mentioned in the last comment).

The resource path logic appears to have been the last blocking issue. I ran the internal googleapis presubmit with #1134 and all the APIs appear to be generate successfully. 😃

**Comment by parthea** [comment]
@busunkim96 Please can you check if there are any outstanding items? If not could we close this issue?
