### ISSUE TITLE
pypi releases

### ISSUE THREAD

**Issue by chickeaterbanana** [googleapis/gapic-generator-python#1057]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
In [pypi](https://pypi.org/project/gapic-generator/) is a old version.

**Describe the solution you'd like**
The current version in pypi.

**Describe alternatives you've considered**
I'm installing it at the moment over git.

**Comment by busunkim96** [comment]
@software-dov for visibility.

There's a GH workflow that's supposed to publish to PyPI (https://github.com/googleapis/gapic-generator-python/blob/master/.github/workflows/pypi-upload.yaml), but it looks like it's broken: https://pypi.org/project/gapic-generator/
