### ISSUE TITLE
Showcase CI tests are always skipped

### ISSUE THREAD

**Issue by vam-google** [googleapis/gapic-generator-python#1147]
An example of a such showcase skipped run: https://github.com/googleapis/gapic-generator-python/runs/4887995943?check_suite_focus=true.

```
Run nox -s showcase
nox > Running session showcase
nox > Session showcase skipped: Python interpreter 3.9 not found.
```

As a result showcase tests are always reported as green even though they never actually ran.

**Comment by software-dov** [comment]
Fixed by #1148
