### ISSUE TITLE
Naming conflict with `create_channel` in 2 generated clients

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#1149]
Unit tests are failing in the generated client for google/cloud/video/livestream/v1 [here](https://github.com/googleapis/googleapis-gen/tree/master/google/cloud/video/livestream/v1/video-livestream-v1-py).

Steps to reproduce

- clone googleapis-gen and cd in to the directory `google/cloud/video/livestream/v1/video-livestream-v1-py`
- run the python post processor image in the root of  `google/cloud/video/livestream/v1/video-livestream-v1-py` using
```
docker run --user $(id -u):$(id -g) --rm -v $(pwd):/repo -w /repo gcr.io/cloud-devrel-public-resources/owlbot-python:latest
```
- run unit tests for python 3.8 with `nox -s unit-3.8`
- The majority of tests fail with `'property' object is not callable`

See stacktrace in screenshot below.

`create_channel` appears in the same class as both a [property](https://github.com/googleapis/googleapis-gen/blob/master/google/cloud/video/livestream/v1/video-livestream-v1-py/google/cloud/video/livestream_v1/services/livestream_service/transports/grpc.py#L249) and a [method](https://github.com/googleapis/googleapis-gen/blob/master/google/cloud/video/livestream/v1/video-livestream-v1-py/google/cloud/video/livestream_v1/services/livestream_service/transports/grpc.py#L183). I believe this is due to the fact that there is an rpc with the name `CreateChannel ` [here](https://github.com/googleapis/googleapis/blob/master/google/cloud/video/livestream/v1/service.proto#L48) which is converted to snake case as `create_channel`.

![Screen Shot 2022-01-24 at 7 35 18 AM](https://user-images.githubusercontent.com/5184014/150783886-1fa9b9d6-21e4-48cd-87d9-4ce192817989.png)

**Comment by parthea** [comment]
This issue also exists in the generated client for eventarc v1 . See the `create_channel` property [here](https://github.com/googleapis/googleapis-gen/blob/master/google/cloud/eventarc/v1/eventarc-v1-py/google/cloud/eventarc_v1/services/eventarc/transports/grpc.py#L434).

**Comment by parthea** [comment]
cc @danoscarmike

**Comment by hkdevandla** [comment]
@software-dov, @vam-google, can you please take a look? Thanks!

**Comment by software-dov** [comment]
Working on this now.
