### ISSUE TITLE
showcase-mtls tests are flaky

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#1208]
In PR https://github.com/googleapis/gapic-generator-python/pull/1207, the `showcase_mtls_alternative_templates` check timed out after 6 hours. See [build log](https://github.com/googleapis/gapic-generator-python/runs/5200587136?check_suite_focus=true). In [this commit](https://github.com/googleapis/gapic-generator-python/pull/1207/commits/c52f043e7a8981c73885f6869237662149ae7eeb), I added `max-parallel: 1` [setting](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel) under `strategy` to limit simultaneous jobs to one. This seems to resolve the issue where the `showcase_mtls_alternative_templates` is stuck. I'm opening this issue as the workaround that I added slows down the pre-submit checks.

**Comment by software-dov** [comment]
Update from 2/17/20: the tests is increasingly flaky to the point where CI must be restarted at least twice to have any chance of passing.

**Comment by parthea** [comment]
https://github.com/googleapis/gapic-generator-python/pull/1212 was merged but let's keep this issue open until  `max-parallel: 1` is removed and the showcase-mtls tests run concurrently.

**Comment by parthea** [comment]
The showcase-mtls tests appear to be flaky even with `max-parallel: 1` and #1212 . See https://github.com/googleapis/gapic-generator-python/pull/1209

**Comment by parthea** [comment]
Closing as duplicate of #1218
