### ISSUE TITLE
Snippetgen: extra newline on docstrings with long descriptions

### ISSUE THREAD

**Issue by dandhlee** [googleapis/gapic-generator-python#1244]
When there is a long description before code blocks, there seems to be an extra newline inserted. 

* Long description not being rendered properly [example link](https://cloud.google.com/python/docs/reference/storagetransfer/latest/google.cloud.storage_transfer_v1.services.storage_transfer_service.StorageTransferServiceClient#google_cloud_storage_transfer_v1_services_storage_transfer_service_StorageTransferServiceClient_run_transfer_job).

**Comment by dizcology** [comment]
Example of two new lines above `.. code-block:: python`: https://github.com/googleapis/python-storage-transfer/blob/main/google/cloud/storage_transfer_v1/services/storage_transfer_service/client.py#L961-L963

While the correct behavior is a single new line, such as: https://github.com/googleapis/python-storage-transfer/blob/main/google/cloud/storage_transfer_v1/services/storage_transfer_service/client.py#L892-L894
