### ISSUE TITLE
snippetgen: resourcemanager_v3.GetIamPolicyRequest type is not defined in the package but is described in the public doc example

### ISSUE THREAD

**Issue by milanmenezes** [googleapis/gapic-generator-python#1263]
https://github.com/googleapis/python-resource-manager/blob/4694fea88edc731f637e1e6d6e2bd860ac06c3a1/google/cloud/resourcemanager_v3/services/projects/client.py#L1464

Public Doc: https://cloud.google.com/python/docs/reference/cloudresourcemanager/latest/google.cloud.resourcemanager_v3.services.projects.ProjectsClient#google_cloud_resourcemanager_v3_services_projects_ProjectsClient_get_iam_policy

**Comment by busunkim96** [comment]
Thanks all for the report.

Almost all request type messages are defined inside the API protos itself, so I wrote the snippetgen code to assume all request messages have the API module name (`resourcemanager_v3`).

I forgot about the IAM methods, which implement the common`google.iam.v1` (https://github.com/googleapis/googleapis/blob/master/google/iam/v1/iam_policy.proto) protos.

https://github.com/googleapis/gapic-generator-python/blob/901e8f0d6592a97c778756ba763ace8561ea3774/gapic/samplegen/samplegen.py#L293-L295

https://github.com/googleapis/gapic-generator-python/blob/901e8f0d6592a97c778756ba763ace8561ea3774/gapic/templates/examples/feature_fragments.j2#L177

A proper fix would require the following:
- A change to [`preprocess_sample`](https://github.com/googleapis/gapic-generator-python/blob/901e8f0d6592a97c778756ba763ace8561ea3774/gapic/samplegen/samplegen.py#L285) to fetch the appropriate `module_name`, probably by looking at the the [rpc](https://github.com/googleapis/gapic-generator-python/blob/901e8f0d6592a97c778756ba763ace8561ea3774/gapic/schema/wrappers.py#L1061) arg.
- A way to add additional imports to the sample. From [this](https://github.com/googleapis/gapic-generator-python/blob/901e8f0d6592a97c778756ba763ace8561ea3774/gapic/samplegen/samplegen.py#L1069) and [this](https://github.com/googleapis/gapic-generator-python/blob/901e8f0d6592a97c778756ba763ace8561ea3774/gapic/templates/examples/sample.py.j2#L27-L28) it looks like there's some support for this in the templates.


This might be tricky to fix quickly, so a temporary option is skipping snippet generation for any of the IAM requests (`SetIamPolicy`, `GetIamPolicy`, `TestIamPermissions`).

Correct version of the sample originally shared:
```py
from google.iam.v1 import iam_policy_pb2
from google.cloud import resourcemanager_v3

def sample_get_iam_policy():
    # Create a client
    client = resourcemanager_v3.ProjectsClient()

    # Initialize request argument(s)
    request = iam_policy_pb2.GetIamPolicyRequest(
        resource="resource_value",
    )

    # Make the request
    response = client.get_iam_policy(request=request)

    # Handle the response
    print(response)
```
