### ISSUE TITLE
Fix comment in proto description for vmImage

### ISSUE THREAD

**Issue by nayaknishant** [googleapis/gapic-generator-python#1285]
Hi, 

This issue (https://github.com/googleapis/python-notebooks/issues/155) states that the [comment for the VmImage project field](https://github.com/googleapis/python-notebooks/blob/fda68e37b126d63f01de81072cebcc783d0077e8/google/cloud/notebooks_v1/types/environment.py#L118) should be `{project_id}` instead of `project/{project_id}`. If we can make this comment change that would be much appreciated.

Nishant

**Comment by parthea** [comment]
Hi @nayaknishant, The issue needs to be addressed in the source proto here:
https://github.com/googleapis/python-notebooks/blob/aed7f52866a9b3c0b1fac8514034fb652246fd02/google/cloud/notebooks_v1/types/environment.py#L116-L118

I've filed b/231030718 for the API team to take a look. I'm going to close this issue as there is no work to be done for the gapic generator.

**Comment by s4shyam95** [comment]
Closing this issue needs the notebook gapic client to be regenerated, else the docstrings will continue being misleading.
