### ISSUE TITLE
Drop dependency on setuptools

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#1316]
The generated code includes a dependency on `setuptools`. It appears that `setuptools` is only needed to get the version of the gapic client via `pkg_resources`. 

See import statement here
https://github.com/googleapis/gapic-generator-python/blob/48c46e3a802ec8d2a69c825b874e73d154a512bf/tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py#L20

and usage here:
https://github.com/googleapis/gapic-generator-python/blob/48c46e3a802ec8d2a69c825b874e73d154a512bf/tests/integration/goldens/asset/google/cloud/asset_v1/services/asset_service/client.py#L1764

We should add a version module to all the GAPIC clients to remove the dependency on `setuptools`.

**Comment by tnguyen14** [comment]
Any update on this?
