### ISSUE TITLE
Snippetgen: PRs are not prefixed with type docs

### ISSUE THREAD

**Issue by dandhlee** [googleapis/gapic-generator-python#1321]
When a snippetgen updates are rolled out, since the types are prefixed with `chore` it does not triggers a release, even though a release is normally required for a docs update.

For example: this PR https://github.com/googleapis/python-scheduler/pull/233 updated problematic snippets, however a docs refresh was not made due to no release being out. Is it possible to have a `docs` type prefixed for these updates, so that the docs are updated in time?

**Comment by parthea** [comment]
Hi @dandhlee, you're right. The change in https://github.com/googleapis/python-scheduler/pull/233 improves the documentation and I should have included a `docs` prefix in order to trigger a release. I'll make sure to include the correct `docs` prefix when there are changes in docstrings.
