### ISSUE TITLE
Docker entrypoint syntax error

### ISSUE THREAD

**Issue by DaniGuardiola** [googleapis/gapic-generator-python#135]
I'm getting this error whenever I run the docker container:

```
/usr/src/gapic-generator-python/docker-entrypoint.sh: line 38: syntax error near unexpected token `;;'
/usr/src/gapic-generator-python/docker-entrypoint.sh: line 38: `      ;;'
```

I changed this line to convert the `else if` into an `elif` because otherwise the `fi` for the second if was missing, and that did the trick.

https://github.com/googleapis/gapic-generator-python/blob/174c508cac20754610e5b39f89f19558a1011fed/docker-entrypoint.sh#L31

Now I don't understand if I'm doing something wrong (I think I'm not) or if this was not tested, but the currently published version in the Docker Hub does not work for me because of this.

**Comment by software-dov** [comment]
Reproduced and verified. Will push a fix momentarily.

**Comment by busunkim96** [comment]
@software-dov Hi! I just ran into this error (using gcr.io/gapic-images/gapic-generator-python:latest). Has the image been re-published since the fix?

**Comment by software-dov** [comment]
Just tagged the 0.11.0 release that should hopefully cause the automation to generate an image with the fix.
