### ISSUE TITLE
fix errors with google-showcase-nspkg.pth

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator-python#1357]
When running tests locally, I get errors of the form

`Error processing line 1 of  /usr/local/google/home/[...]/gapic-generator-python/.nox/showcase_alternative_templates/lib/python3.9/site-packages/google-showcase-nspkg.pth`

Not sure where that line is coming from (maybe `nox`, maybe Showcase itself), but we should fix the error which is causing tests to fail. Apparently the workaround is to manually remove the file, but we should not need to do that.

**Comment by vam-google** [comment]
This is the site packages issue which has caused many different issues for us. Some details about it: https://github.com/googleapis/gapic-generator/issues/3334#issuecomment-768156415.

**Comment by parthea** [comment]
I believe this should be resolved now that we've removed `namespace_packages` from setup.py. See related discussion in https://github.com/googleapis/gapic-generator/issues/3334#issuecomment-768156415. I'm going to close this issue. We can open it again if the issue reappears.
