### ISSUE TITLE
fix "error processing line 1 of google-showcase-nspkg.pth"

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator-python#1361]
Running nox showcase test suites leads to errors of the form
`Error processing line 1 of /usr/local/google/home/…/gapic-generator-python/.nox/showcase_alternative_templates/lib/python3.9/site-packages/google-showcase-nspkg.pth`

A workaround is to go to the offending file and insert a newline after the `import` statement. However, I've seen the problem recur on subsequent test runs.

We should figure out where that file is coming from and fix it. 

It may be originating from setuptools, since it seems to appears upon setup/installation, but I am not at all sure about that.

This affects test coverage, code hygiene, developer productivity, developer efficiency/satsifaction.

**Comment by parthea** [comment]
I believe this should be resolved now that we've removed `namespace_packages` from setup.py. See related discussion in https://github.com/googleapis/gapic-generator/issues/3334#issuecomment-768156415. I'm going to close this issue. We can open it again if the issue reappears.
