### ISSUE TITLE
Dictionary support not reflected in type annotations

### ISSUE THREAD

**Issue by PicardParis** [googleapis/gapic-generator-python#1380]
## Issue

- This is a follow-up to [#986](https://github.com/googleapis/gapic-generator-python/issues/986) (closed). Retesting the recent `google-cloud-documentai==1.5.0` version, the issue is still present.
- This code is valid:
  ```
  import google.cloud.documentai_v1 as documentai

  client_options = dict(api_endpoint="eu-documentai.googleapis.com")
  client = documentai.DocumentProcessorServiceClient(client_options=client_options)
  ```
- But it triggers the following type checker warning:
  ```
  Argument of type "dict[str, str]" cannot be assigned to parameter "client_options" of type "ClientOptions | None" in function "__init__"
  Type "dict[str, str]" cannot be assigned to type "ClientOptions | None"
  "dict[str, str]" is incompatible with "ClientOptions"
  ```
- If you check the [source](https://github.com/googleapis/python-documentai/blob/1b4eff4e0f6ca34bd12fb5cd01343ca74b4f9633/google/cloud/documentai_v1/services/document_processor_service/client.py#L366), `client_options` can be a dict, yet its declaration says otherwise:
  ```python
  def __init__(
      ...
      client_options: Optional[client_options_lib.ClientOptions] = None,
      ...
  ) -> None:
      ...
      if isinstance(client_options, dict):
          client_options = client_options_lib.from_dict(client_options)
  ```

## Expected

  ```python
  def __init__(
      ...
      client_options: Union[client_options_lib.ClientOptions, dict, None] = None,
      ...
  ) -> None:
      ...
  ```

**Comment by atulep** [comment]
@PicardParis 

Yup, your code looks good. Feel free to open a PR. Otherwise, my team will triage this issue and resolve it, but may take longer.

**Comment by PicardParis** [comment]
Hi, I thought the library was auto-generated from protobufs. Please confirm that it's not and I'll make a PR.

**Comment by vam-google** [comment]
@PicardParis The library is generated, so the change should be done not in the lib, but in gapic-generator-python (i.e. this repository) instead. The changes are most likely to happen in one of the template files (`*.py.j2` files). I would look into changing somethign here: https://github.com/googleapis/gapic-generator-python/blob/main/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/client.py.j2#L279

**Comment by PicardParis** [comment]
@atulep @vam-google
- Thanks for the explanation & pointer
- I made the tentative [PR#1431](https://github.com/googleapis/gapic-generator-python/pull/1431)
