### ISSUE TITLE
Update top-level README 

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator-python#1391]
The top-level `README.rst` is very sparse, and it says that the repository "primarily exists to facilitate experimentation", which is no longer true.

We should update the file to say this library is used for official client libraries. Moreover, we should consider whether to add slightly more information to the `README.rst`, even though it seems proper to refer people to [ReadTheDocs](https://googleapis.dev/python/gapic-generator-python/latest/index.html) for the bulk of the documentation. (See also issue #1390 about auditing that documentation, too.)

**Comment by ohmayr** [comment]
Closing this issue since the primary concern to remove the experimentation part has been addressed here: <https://github.com/googleapis/gapic-generator-python/commit/00e8579aa4a9e98341cafded0e7e477baab6e71c>

Note: The `README.rst` can be updated as we identify more things that we need to document.
