### ISSUE TITLE
Header x-goog-api-client is not set to indicate REST transport

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator-python#1392]
In the course of developing another feature and testing it against a local Showcase server, I found that we are not setting the value of the `X-Goog-Api-Client` to contain a token `rest/XXX`. The `XXX` is an arbitrary version label, meant to denote what version of REST we're using. In our case, our main REST code is in the library itself, so it probably makes the most sense to use the gapic-generator-python version number there. If that's not available right now, we can use a placeholder like "0.0.1" for now.

For context, this is the error Showcase currently reports:
```
REST request failed format check: (HeaderAPIClientError) did not find expected HTTP header "X-Goog-Api-Client": "rest/"
```

**Comment by vchudnov-g** [comment]
@noahdietz FYI. LMK of any concerns.

**Comment by noahdietz** [comment]
> our main REST code is in the library itself, so it probably makes the most sense to use the gapic-generator-python version number there

The version of the generator that generated that client? Or the version of the client library itself?

**Comment by vchudnov-g** [comment]
Arg. Sorry, tagged you on the wrong issue.

But anyway, yes, version of the generator.

**Comment by vchudnov-g** [comment]
I can't reproduce this at the moment. I generated a Showcase Python GAPIC and ran it against the local Showcase server, and it seems to work. It would be getting an error if the header were absent. I must have gotten confused when I filed this and looked at the output from some sort of manual request.
