### ISSUE TITLE
verify generated libraries work when transport=rest

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator-python#1404]
This should involve at least one and ideally both of
- running generated unit tests on the generated clients
- running the generated clients against a real server, either via an integration test or manually 

The above should be done both for clients using the Ads templates and clients using the regular templates, and should cover cases when numeric enums are enabled or disabled.

This should be a prerequisite for GAing rest transport.

**Comment by parthea** [comment]
Bumping to P2 as we have manual integration tests in downstream repositories

**Comment by vchudnov-g** [comment]
Refined this into two more narrowly scoped separate issues, #1426 and #1427. Closing this.
