### ISSUE TITLE
Generated RestTransport leads to incorrect initialization of OperationsRestTransport

### ISSUE THREAD

**Issue by pearcemc** [googleapis/gapic-generator-python#1491]
We have a service in private alpha. I have used the gapic generator to produce a py client (thanks, it's good!).
However it seems the generated client does not correctly initialize its OperationsRestTransport [1].

In particular, the current behavior leads to the error at the end of this flow:

```python
host = "my-alpha-service.goog"      # some private dns
rest = MyAlphaServiceRestTransport(host=host)
client = MyAlphaServiceClient(transport=rest)

type(client._transport.operations_client._transport)
# google.api_core.operations_v1.transports.rest.OperationsRestTransport

client._transport.operations_client._transport._host
# 'https://my-alpha-service.goog'

op = client.function_returning_lro(some_request)
# ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //my-alpha-service.goog/v1alpha1/{{REDACTED}}/operations/import-a3106bbf-2298-4894-bc38-31bbe520533d
```

This can be resolved by ensuring at [2] that something equivalent to the following happens:

```
# match object from __init__
schemeless_host = maybe_url_match.group('host') 

rest_transport = operations_v1.OperationsRestTransport(
  host=schemeless_host,
  # use the credentials which are saved
  credentials=self._credentials,
  scopes=self._scopes,
  http_options=http_options)
```

I changed the ` MyAlphaServiceRestTransport` code generated by `rest.py.j2` to this effect. 
Then went through the same flow again but with the expected outcome:

```python
rest_alt = MyAlphaServiceAltRestTransport(host=host)
client_alt = MyAlphaServiceClient(transport=rest_alt)

client_alt._transport.operations_client._transport._host
# 'my-alpha-service.goog:443'

op = client.function_returning_lro(some_request)
op.result()
# OK - returns the expected response_type proto
```

[1] https://github.com/googleapis/gapic-generator-python/blob/f8bc1c69dc19c7d0ea973370c283e84e5abae5b7/gapic/ads-templates/%25namespace/%25name/%25version/%25sub/services/%25service/transports/rest.py.j2#L202
[2] https://github.com/googleapis/gapic-generator-python/blob/f8bc1c69dc19c7d0ea973370c283e84e5abae5b7/gapic/ads-templates/%25namespace/%25name/%25version/%25sub/services/%25service/transports/rest.py.j2#L249

**Comment by atulep** [comment]
Interesting. Thanks for the report. Does `schemeless_host = maybe_url_match.group('host')` essentially solve the issue here ?

**Comment by pearcemc** [comment]
Yup. 
(Though I didn't test with alternate url schemes, like `http://foo.goog` etc). Just `https` case.

**Comment by vchudnov-g** [comment]
@pearcemc Is this still happening? I am trying to reproduce this problem with the speech API (see [gist](https://gist.github.com/vchudnov-g/5cef8d6f44c7020d836c950d92b4e1af)), and I'm not able to. I'm curious whether there's something particular about your API/set-up that I'm overlooking.

(As that gist shows, I'm encountering a different error. I filed an internal issue, but I'll file one in GitHub as well.)

**Comment by pearcemc** [comment]
This seems to be fixed upstream now. In that I built a fresh client and the previously failing `op.result()` call no longer fails.

**Comment by vchudnov-g** [comment]
OK, thanks for the update. I will close this issue, then. Thanks for reporting this, and please continue to report any further problems you encounter.
