### ISSUE TITLE
Bug issue in google.cloud.servicedirectory_v1.types.namespace.Namespace.__eq__ class

### ISSUE THREAD

**Issue by msampathkumar** [googleapis/gapic-generator-python#1500]
Thanks for stopping by to let us know something could be better!

#### Environment details

OS: Google Cloud Shell
pip version: google-cloud-service-directory==1.5.3

For more details, please check
* https://github.com/GoogleCloudPlatform/python-docs-samples/issues/8431
* http://b/254626764

#### Steps to reproduce

  1. Create a namespace object,  `namespace`
  2. Get a list of all namespace objects, say `temp`
  3. Check if `namespace` is in `temp`

#### Code example

Please check http://b/254626764#comment10

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by atulep** [comment]
Looks like referenced PR and bug were resolved. Closing this down.
