### ISSUE TITLE
Server streaming methods are not properly marked as async

### ISSUE THREAD

**Issue by Mariatta** [googleapis/gapic-generator-python#1503]
As found in https://github.com/googleapis/python-bigtable/pull/702/files#diff-cefca7c885a9bf43a6cc4769c788d30041fcffc582df926b7240e03beea308ebR529

In google/cloud/bigtable_v2/services/bigtable/async_client.py file, `mutate_rows` should become a coroutine. i.e. `async def mutate_rows`.

and the call to the rpc should be awaited. i.e. `await rpc(...`

**Comment by vchudnov-g** [comment]
@daniel-sanche Any insights on this? Is this still an issue for BigTable? Are there changes we should incorporate in the generated GAPICs?

**Comment by cindy-peng** [comment]
Hi

> @daniel-sanche Any insights on this? Is this still an issue for BigTable? Are there changes we should incorporate in the generated GAPICs?

Hi Victor, Daniel is out of office today. He will be back next week and should be able to help investigate.

**Comment by daniel-sanche** [comment]
I remember discussing this with Mariatta long ago, and came down to a misunderstanding. 

The server streaming methods are implemented as a sync function that returns an async generator, rather than as an async generator function. But the end result works the same

This can be closed
