### ISSUE TITLE
annotations subscripting containers cause TypeErrors

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator-python#1607]
As per an internal doc,  subscripting  a container that does not inherit from `typing.Generic` can cause errors. In particular, a `MutableSequence` indexed by  enums causes an error of the form
`TypeError: Parameters to generic types must be types`. This can be triggered, for example, by code of the form

```
        days_of_week: MutableSequence[dayofweek_pb2.DayOfWeek] = proto.RepeatedField(
            proto.ENUM,
            number=2,
            enum=dayofweek_pb2.DayOfWeek,
        )
```

which we are seeing in the internal part of our publishing pipeline.

Either of these fixes by itself works:
1. Quoting the type: `MutableSequence['dayofweek_pb2.DayOfWeek']`
2. Adding `from __future__ import annotations ` at the top of the file. As per an internal reference, this seems to be related to [PEP563](https://peps.python.org/pep-0563/), which has a status of `Accepted` as of 2017, so it's not clear why we would need a fix in the first place.

We should decide and implement the right fix.

**Comment by atulep** [comment]
> from __future__ import annotations

looks reasonable.

**Comment by vchudnov-g** [comment]
Apparently PEP 563 was rolled back from Python3.10: See this [Reddit discussion](https://www.reddit.com/r/Python/comments/muyz5h/pep_563_getting_rolled_back_from_python_310/) and [Python.org discussion](https://mail.python.org/archives/list/python-dev@python.org/thread/CLVXXPQ2T2LQ5MP2Y53VVQFCXYWQJHKZ/), which say that due to compatibility concerns, making PEP563 be the default will not happen until Python3.11.

**Comment by vchudnov-g** [comment]
Reading more about "future statements" in the [doc](https://mail.python.org/archives/list/python-dev@python.org/thread/CLVXXPQ2T2LQ5MP2Y53VVQFCXYWQJHKZ/), it seems that "All historical features enabled by the future statement are still recognized by Python 3" and are "only kept for backwards compatibility", so presumably this will continue to be the case in the future. In that case, the future statement solution seems like a correct and easy fix.
