### ISSUE TITLE
_client_info 'except' block is not tested

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#171]
This 'except' block is the only line missing unit test coverage. 

```
try:
    _client_info = gapic_v1.client_info.ClientInfo(
        gapic_version=pkg_resources.get_distribution("google-cloud-workflows").version
    )
except pkg_resources.DistributionNotFound:
    _client_info = gapic_v1.client_info.ClientInfo()
```

https://github.com/googleapis/google-cloud-python-private/blob/530c9c710b768c444eba4bd7c8639096affae89a/workflows/google/cloud/workflows_v1alpha1/services/workflows/client.py#L431

**Comment by lukesneeringer** [comment]
Right now, we generate [a `.coveragerc` file](https://github.com/googleapis/gapic-generator-python/blob/master/gapic/templates/.coveragerc.j2) which omits that line.

That line is _really_ tough to test. It is module level, not function level (and should be).

I assume you are plowing over our `.coveragerc` with synthtool. That makes sense to me, but do you think it would be possible to add that to your `exclude_lines`?

**Comment by busunkim96** [comment]
Ah, I forgot we had `.coveragerc` in our templates. I'll make that change. Thank you. :)

**Comment by tseaver** [comment]
Somehow, the templated `.coveragerc` file is *not* being [generated for Firestore via synthtool](https://github.com/googleapis/python-firestore/blob/1cd8f93860cc9a72dadcee78dee59d073cbe8507/.coveragerc).

**Comment by busunkim96** [comment]
@tseaver The missing .coveragerc issue is tracked in #437
