### ISSUE TITLE
Add baseline comparison files for generated sample output

### ISSUE THREAD

**Issue by software-dov** [googleapis/gapic-generator-python#179]
Include baseline sample files generated via a combination of a dummy api proto and some reasonably feature-comprehensive sample configs.

In an ideal world, these are autogenerated, either via git-hook magic or ci magic. If they cannot be autogenerated, then they are used in comparison tests so that editors are forced to keep them up to date.

**Comment by lukesneeringer** [comment]
Wait, are we suggesting baseline tests? I would really prefer not...baseline tests are not a particularly good testing practice.

**Comment by software-dov** [comment]
Not exactly baseline tests, but those would be the effective fallback.
This came up during yesterday's Samplegen meeting, but Yoshi doesn't care about generator internals; they only care about modifications to the generated output, and when someone posts a PR they want to see what the deltas to the generated output would be. The _ideal_ way to do that would be to have e.g. the library API or showcase API proto and a well fleshed out sample config file as part of the repo, plus the corresponding generated samples that devrel can inspect and infer surface changes.
It is laughable to expect developers to keep these generated samples up to date by hand, so in an ideal world these would be kept up to date via a git pre-commit hook, or some CircleCI magic. Using baseline tests would be if neither of the first two wind up being doable.
