### ISSUE TITLE
Some types are not exported in __init__.py

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#185]
I generated Natural Language ([see PR](https://github.com/googleapis/google-cloud-python/pull/9063)) and re-wrote a sample file.

`EncodingType` is not available under  [`language_v1`](https://github.com/googleapis/google-cloud-python/blob/824af57d04e88ac8c7aa0879aff1793ebbd039c2/language-microgenerator/google/cloud/language_v1/__init__.py#L27-L51) or [`language`](https://github.com/googleapis/google-cloud-python/blob/824af57d04e88ac8c7aa0879aff1793ebbd039c2/language-microgenerator/google/cloud/language/__init__.py#L31-L55). I'm not sure if this is why it is missing, but `EncodingType` is a `proto.enum` class, while the others are `proto.message`. (see [language_service.py](https://github.com/googleapis/google-cloud-python/blob/824af57d04e88ac8c7aa0879aff1793ebbd039c2/language-microgenerator/google/cloud/language_v1/types/language_service.py)).

```Python
from google.cloud import language_v1
# separate import to get EncodingType?
from google.cloud.language_v1.types.language_service import EncodingType

def sample_analyze_sentiment(content):

    client = language_v1.LanguageService()

    # content = "Your text to analyze, e.g. Hello, world!"

    type_ = language_v1.Document.Type.PLAIN_TEXT
    document = language_v1.Document(type=type_, content=content)
    request = language_v1.AnalyzeSentimentRequest(
        document=document, encoding_type=EncodingType.UTF8
    )

    response = client.analyze_sentiment(request)
    sentiment = response.document_sentiment

    print("Score: {}".format(sentiment.score))
    print("Magnitude: {}".format(sentiment.magnitude))
```

**Comment by software-dov** [comment]
I'm not sure I understand what the problem is. Is there an error, or is it that you think all wrapped types should be visible through `language_v1`?

**Comment by busunkim96** [comment]
@software-dov No errors, it would just  be nicer if all the types are visible.
