### ISSUE TITLE
improve the generated unit tests 

### ISSUE THREAD

**Issue by mukund-ananthu** [googleapis/gapic-generator-python#1937]
1. Currently, the warnings are bubbling up and blocking submission of PRs like: https://github.com/googleapis/python-pubsub/pull/1064
2. Affected issue: https://github.com/googleapis/gapic-generator-python/issues/1938

**Comment by parthea** [comment]
Since these issues are captured in #1938 and #1939, I'm closing this issue as a duplicate.
