### ISSUE TITLE
Add support for protobuf 5.x

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#1996]
Protobuf 5.x is not currently supported in generated clients.

See blocking issue https://github.com/googleapis/proto-plus-python/issues/431

https://github.com/googleapis/gapic-generator-python/blob/24a23a1ab885246e447c0010b2e5602209dfbb8d/setup.py#L27-L35

and
https://github.com/googleapis/gapic-generator-python/blob/24a23a1ab885246e447c0010b2e5602209dfbb8d/gapic/templates/setup.py.j2#L32-L39

As part of this upgrade, we should drop support for protobuf 3.x, and deprecate support for 4.x shortly after 5.x has been released in generated clients.

**Comment by vchudnov-g** [comment]
One custoemr issue that would benefit from this: https://github.com/googleapis/google-cloud-python/issues/12560
