### ISSUE TITLE
async client does not support explicit routing

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/gapic-generator-python#2091]
A python-datastore user [recently reported](https://github.com/googleapis/python-datastore/issues/544#event-13103173857) that the async client is missing some routing headers added to the sync client, making it unusable

Sync ([link](https://github.com/googleapis/python-datastore/blob/5e773cb8c766303fef53965dd100b3c4c93b98be/google/cloud/datastore_v1/services/datastore/client.py#L765C1-L776C14)):
```
header_params = {}

if request.project_id:
    header_params["project_id"] = request.project_id

if request.database_id:
    header_params["database_id"] = request.database_id

if header_params:
    metadata = tuple(metadata) + (
        gapic_v1.routing_header.to_grpc_metadata(header_params),
    )
```

Async ([link](https://github.com/googleapis/python-datastore/blob/5e773cb8c766303fef53965dd100b3c4c93b98be/google/cloud/datastore_v1/services/datastore/async_client.py#L368)):
```
metadata = tuple(metadata) + (
    gapic_v1.routing_header.to_grpc_metadata(
        (("project_id", request.project_id),)
    ),
)
```

**Comment by daniel-sanche** [comment]
It seems like the async client doesn't support [explicit_routing](https://github.com/googleapis/gapic-generator-python/blob/b64e7a3351804613aaf56d7a699390d8dbc70712/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/_client_macros.j2#L147)?

**Comment by daniel-sanche** [comment]
Related issue: https://github.com/googleapis/gapic-generator-python/issues/1757 discusses the performance cost of the regex verification. But also addresses that the generated output is different

**Comment by adrianwbsf** [comment]
Hi @daniel-sanche, do you have any updates on the issue? Will this issue make selecting the database possible?

**Comment by daniel-sanche** [comment]
Hey, no concrete updates yet, but it's being looked at!
