### ISSUE TITLE
docs: Add documentation for request / response interceptors for `gRPC` transport.

### ISSUE THREAD

**Issue by ohmayr** [googleapis/gapic-generator-python#2191]
request / response interceptors are currently not supported for `gRPC`. We need to add support for this and also update the relevant unit tests to ensure that we have code coverage.

**Comment by parthea** [comment]
I've switched this issue from `bug` to `docs` as interceptors are a feature of gRPC and are already implemented. We need to add the relevant tests and documentation.

**Comment by parthea** [comment]
This should be part of product agnostic documentation (b/381043501)
