### ISSUE TITLE
[async rest] Update the minimum version of `core` in async rest option

### ISSUE THREAD

**Issue by ohmayr** [googleapis/gapic-generator-python#2208]
We're currently using the pre-release version of `google-api-core` i.e. `2.21.0rc0` in the `async_rest` option in `setup.py.j2`. Update it to `2.21.0` when released.

Also update the noxfile for the generator where we're using the pre-release version.

**Comment by parthea** [comment]
Version `2.21.0` was released today

https://pypi.org/project/google-api-core/2.21.0/
