### ISSUE TITLE
Add generated library documentation

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#228]
Generated libraries should have a directory `docs/` with the following structure:

See https://github.com/googleapis/google-cloud-python-private/tree/51c5cb1fe90f258169b0b7622c7fa10758014b70/billing_budgets/docs
```
docs/
  conf.py  # configuration for Sphinx
  index.rst  # ToC to other docs
  budgets_v1alpha1/
     services.rst
     types.rst
```

This will allow docs to continue to be generated with sphinx.

**Comment by software-dov** [comment]
Fixed by #272
