### ISSUE TITLE
kiosk/__init__.py: Tried to write the same file twice.

### ISSUE THREAD

**Issue by timburks** [googleapis/gapic-generator-python#26]
Running in [kiosk/protos](https://github.com/googleapis/kiosk/tree/master/protos) (after having run `COMPILE-PROTOS.sh` in the parent directory), I get this message:
```
$ protoc kiosk.proto --proto_path=./api-common-protos --proto_path=. --pyclient_out=.
kiosk/__init__.py: Tried to write the same file twice.
```
This is with no configuration options, so I'm not surprised that it failed, but was surprised by the type of problem. Are there error messages that I can watch for? (`protoc` plugins can write errors to stdout)

**Comment by lukesneeringer** [comment]
I filed #27 to fix this problem.

I also looked at the output to `kiosk` and this exposed a couple of other bugs, one major and one minor. Filing separate bugs for those.

**Comment by lukesneeringer** [comment]
One issue I noticed is a (pretty critical) import mismatch. Filed #28 to fix it and documented a workaround there.

**Comment by lukesneeringer** [comment]
Another issue I noticed is a silly package name due to not being careful about the existence of the namespace. Filed #29 to fix it. No workaround at this time, but a fix will be coming shortly.
