### ISSUE TITLE
Add test coverage for trailing metadata from server streaming methods

### ISSUE THREAD

**Issue by software-dov** [googleapis/gapic-generator-python#280]
This is blocked by sending the metadata from the showcase server: [gapic-showcase/issues/278](https://github.com/googleapis/gapic-showcase/issues/278)

**Comment by noahdietz** [comment]
Showcase will actually echo back incoming metadata keyed by `showcase-trailer` as Trailing Metadata in the response, so https://github.com/googleapis/gapic-showcase/issues/278 has been closed.

**Comment by arithmetic1728** [comment]
tests added, close the issue.
