### ISSUE TITLE
Generated library cannot be installed with python 3.5

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#292]
@dizcology was unable to install a generated library with Python 3.5 because the required dependency libcst requires 3.6+. https://github.com/Instagram/LibCST/blob/master/setup.py#L37

I am fine supporting only 3.6+ since [3.5 goes EOL in September](https://devguide.python.org/#status-of-python-branches).

Thoughts?

@software-dov @crwilcox

**Comment by software-dov** [comment]
Mea culpa :P I don't think that's our decision to make; the summary judgement would be to yank the conversion script, which would be a shame.
Personally, I'm in favor of dropping 3.5.

**Comment by busunkim96** [comment]
Same, I think the benefit of having the conversion script outweighs 3.5 support.

Also @BenRKarl since the Ads folks may be interested.

**Comment by BenRKarl** [comment]
I'm ok to drop 3.5 - our library requires 3.7+ so that's what I am usually using, but I'm totally fine with whatever you all decide.

**Comment by software-dov** [comment]
CCing @AlanGasperini @JustinBeckwith @hkdevandla

**Comment by software-dov** [comment]
Is that a "thumbs up for dropping 3.5 support" or a "thumbs up for reaching out"?

**Comment by JustinBeckwith** [comment]
Hah, I am personally ok with dropping 3.5 support, if that's what @busunkim96 thinks is the right thing to do.

**Comment by AlanGasperini** [comment]
Do we have anything documented(even if just internally) about what versions we intend to support?

**Comment by software-dov** [comment]
From the oral history I remember a commitment to support 3.5. It is not included in the unit test suite because the _generator_ requires features from >=3.6 , and it is nontrivial within nox to run the generator via one python version and run the unit tests via another.

**Comment by busunkim96** [comment]
Following up on this - I think the commitment to 3.5 was made when we thought the transition would be earlier in the year. At this point it is looking like March at the earliest, and realistically April for most libraries. 

I will document the >=3.5 support in the microgenerator rollout/acceptance document. Could the template's setup.py be updated with the more restrictive version range?

**Comment by software-dov** [comment]
Tracked by #308

**Comment by software-dov** [comment]
Implemented by #309 in so far as that there is no ambiguity: 3.5 support has been dropped from the generated surface.
