### ISSUE TITLE
[Python] Generate default class docstring when needed

### ISSUE THREAD

**Issue by bjwatson** [googleapis/gapic-generator-python#366]
If a class docstring does not exist, then Sphinx will not generate a documentation page for that class. Arguably this is a bug in Sphinx, but it's one we need to work around.

This happens for us when the proto file does not have a comment describing the service. One example is `logging_config.proto` and `logging_metrics.proto` for the Logging API. I added service level comments in the https://github.com/googleapis/googleapis repo, but the upstream source does not have them.

We should enhance our surface generator to be robust about this, and generate a default docstring when the service does not have a comment. We should also emit a warning in the generator output.

**Comment by software-dov** [comment]
Not an issue for the microgenerator.
