### ISSUE TITLE
Properly format manual sample code

### ISSUE THREAD

**Issue by bjwatson** [googleapis/gapic-generator-python#367]
For example, see http://pythonhosted.org/gax-google-pubsub-v1/google.protobuf.timestamp_pb2.html#module-google.protobuf.timestamp_pb2. This manually written sample code is poorly formatted in the Python doc.

We will probably need some kind of hint in the proto file that it's sample code, such as the markdown conventional ```.

**Comment by software-dov** [comment]
Out of scope for microgenerator.
