### ISSUE TITLE
What Python packages should be declared as namespace packages?

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator-python#370]
### What

The current behavior is to declare all gRPC and GAPIC packages as namespace packages *except* the version package; that is, for an API living in the package `google.cloud.foo.bar.v1`, we will declare all packages as namespace packages except `v1`. This behavior originated in [Packman](https://github.com/googleapis/packman/blob/378f7c479df0e0f7d243d06d48c4a60db5c47621/lib/packager.js#L223) and has been ported to Toolkit.

Currently, it's always necessary to declare `google`, `google.cloud`, `google.cloud.grpc`, and `google.cloud.gapic` as namespace packages, as these are shared across many packages on PyPI that may be installed together. Declaring deeper packages as namespace packages is not necessary, but not harmful either, AFAIK, and opens up the possibility of splitting up types across multiple packages, which may be an important future use case (as we've seen with the logging `AuditData` types).

Do we need special logic for the version package?

### Why
- Not declaring the version package as a namespace package allows us to declare package-level types in the version-level `__init__.py`. This may have been the original rationale for this strategy
- We don't currently use the `__init__.py` to define anything, so we can simplify the packaging logic by simply declaring all packages as namespace packages.

cc: @bjwatson @lukesneeringer

**Comment by software-dov** [comment]
I don't think this is relevant to the microgenerator.
