### ISSUE TITLE
Documentation links to cloud.google.com are incorrect

### ISSUE THREAD

**Issue by geigerj** [googleapis/gapic-generator-python#375]
### What

Currently client library documentation contains autogenerated links to cloud.google.com. The URLs are derived heuristically, and are sometimes incorrect. For example, autogenerated Natural Language docs point to https://cloud.google.com/language/ instead of the expected https://cloud.google.com/natural-language/ ([context](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1856)).

### How

These URLs are already specified by internal configuration metadata. We need to open source this configuration and consume it in the code generation process.

**Comment by software-dov** [comment]
Bug is too vague, and in the microgenerator documentation is provided via proto files. Links are not constructed heuristically. Marking as closed.
