### ISSUE TITLE
[Python] Improve documentation for service constructor arguments

### ISSUE THREAD

**Issue by bjwatson** [googleapis/gapic-generator-python#376]
### What:

Improve documentation for service constructor arguments, and make it clear that they are all optional.

Also fix links to supporting objects, such as `grpc.beta.implementations.Channel`, `grpc.beta.implementations.ClientCredentials`, and `google.gax.construct_settings()` in the [Sphinx rendered documentation](http://pythonhosted.org/gax-google-pubsub-v1/google.pubsub.v1.publisher_api.html#google.pubsub.v1.publisher_api.PublisherApi).

This is _not_ the same as https://github.com/googleapis/toolkit/issues/197, which refers to method call options.
### Why:

They are standard across our auto-generated Python surfaces, and the purpose of the arguments is not obvious. For example, why would I change `service_path` or `port`?
### How:

This is mostly a documentation effort. @omaray do you have any thoughts on this?

**Comment by software-dov** [comment]
Ctor arguments are better documented in the microgenerator.
