### ISSUE TITLE
[Python] Move __init__ documentation to class docstring

### ISSUE THREAD

**Issue by bjwatson** [googleapis/gapic-generator-python#377]
### What:
- Move content of `__init__` docstring to class docstring for a service (see http://pythonhosted.org/gax-google-pubsub-v1/_modules/google/pubsub/v1/publisher_api.html#PublisherApi).
- Remove the superfluous "Constructor" title
- Remove the unnnecessary "Returns" section
### Why:

Per @jonparrott, "most libraries actually document the constructor in the class docstring, so I would advise putting the args section here into the class docstring and omitting the docstring for the `__init__` method. Typically you don't want to separately document `__init__` unless there is more than one way to construct the class (e.g. `@classmethod` helper constructors)."

[PEP 257](https://www.python.org/dev/peps/pep-0257/) indicates that the `__init__` method should have a docstring, but the class docstring is effectively the `__init__` docstring.
### How:

Update appropriate generator `.snip` code.

Ensure that Sphinx is configured correctly: http://www.sphinx-doc.org/en/stable/ext/autodoc.html#confval-autoclass_content

Create a corresponding issue in https://github.com/googleapis/gax-python to do whatever we do here, for consistency.

**Comment by software-dov** [comment]
De facto fixed in microgenerator.
