### ISSUE TITLE
Samplegen: Streaming in Python Speech-to-Text

### ISSUE THREAD

**Issue by nnegrey** [googleapis/gapic-generator-python#378]
@googleapis/samplegen 

[speech_streaming.yaml](https://paste.googleplex.com/5401745645633536)

[speech_streaming.py](https://paste.googleplex.com/4637460141178880)

[handwritten_speech_streaming.py](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/speech/cloud-client/transcribe_streaming.py)

Error:
```
Traceback (most recent call last):
  File "samples/v1/speech_streaming_recognize.py", line 80, in <module>
    main()
  File "samples/v1/speech_streaming_recognize.py", line 77, in main
    sample_streaming_recognize(args.path)
  File "samples/v1/speech_streaming_recognize.py", line 48, in sample_streaming_recognize
    for response_item in client.streaming_recognize(requests):
TypeError: streaming_recognize() missing 1 required positional argument: 'requests'
```

Cause:
Generated: `client.streaming_recognize(requests)`
Handwritten: `client.streaming_recognize(streaming_config, requests)`

Reason: Handwritten Layers.
https://github.com/googleapis/google-cloud-python/blob/master/speech/google/cloud/speech_v1/helpers.py

**Comment by software-dov** [comment]
Don't think this is relevant to the microgenerator.
