### ISSUE TITLE
[Python] "400 Request is missing 'x-goog-request-params' header" when using dictionary as parameter in functions that use routing headers

### ISSUE THREAD

**Issue by tswast** [googleapis/gapic-generator-python#380]
See: https://github.com/googleapis/google-cloud-python/issues/7220 for how this manifests in the BigQuery Storage API.

**Comment by hkdevandla** [comment]
@software-dov, can you triage this? I'm not sure if this still an issue in the new python micro-generator. Please advice.

**Comment by software-dov** [comment]
Duplicate of #401
