### ISSUE TITLE
Python: setup.py hardcoded google.cloud namespace

### ISSUE THREAD

**Issue by jpoehnelt** [googleapis/gapic-generator-python#382]
I am trying to generate python code for `google/maps/*` and the namespace in the setup.py always adds `google.cloud`.

See these lines: https://github.com/googleapis/gapic-generator/blob/master/src/main/resources/com/google/api/codegen/py/setup.py.snip#L48-L49

**Comment by software-dov** [comment]
The microgenerator does not mandate `google.cloud` in setup.py or the rest of the generated surface.
