### ISSUE TITLE
[AsyncIO] Adding async client support to the Ads templates

### ISSUE THREAD

**Issue by lidizheng** [googleapis/gapic-generator-python#385]
Originated from https://github.com/googleapis/gapic-generator-python/pull/365

@software-dov Can you fill-in more information about the templates? Does Ads team use separate sets of templates than normal the GAPIC microgenerator?

**Comment by software-dov** [comment]
Yes, they have a separate set of templates under the `gapic-generator-python/gapic/ads-templates` directory. They are mostly the same,but there's a directory structure change they require that prompted the parallel set of templates.
