### ISSUE TITLE
Fetching @gapic_generator_python_pip_deps takes 5+ minutes

### ISSUE THREAD

**Issue by aohren** [googleapis/gapic-generator-python#400]
Breaking this out as a separate issue from #361 (where I first mentioned this). 

When trying to build the `py_gapic_library` Bazel rule, the `Fetching @gapic_generator_python_pip_deps` step takes a little >5 mins from a clean build every time. 

Reproducible by doing  `bazel clean --expunge` before building.

**Comment by hkdevandla** [comment]
I guess @vam-google is looking into this. Vadym, please update with your findings.
