### ISSUE TITLE
feat: Allow client to connect over plaintext

### ISSUE THREAD

**Issue by kristofarkas** [googleapis/gapic-generator-python#406]
It would be nice to have an option to generate a client that can connect over plaintext to the server. Especially during development.

I couldn't find a way to do this, is it possible?

**Comment by software-dov** [comment]
By 'plaintext' do you mean http instead of gRPC? If so, then that's already being tracked by #267

**Comment by kristofarkas** [comment]
E.g. if you start the grpc server with an insecure port (`server.add_insecure_port `) be able to connect to with the generated client. Usually you can do it with a client like this: `grpc.insecure_channel`, but some implementations (Java, or the grpcurl utility) need to be set to `usePlainText` and `-plaintext`.
