### ISSUE TITLE
Instability in location of resource path methods

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#429]
Examples:
* https://github.com/googleapis/python-recaptcha-enterprise/pull/11/files
* https://github.com/googleapis/python-game-servers/pull/16/files
* https://github.com/googleapis/python-bigquery-reservation/pull/16/files

The resource path helper methods are being re-ordered with no change to the underlying protos or generator version.

**Comment by miraleung** [comment]
@software-dov PTAL?

**Comment by hkdevandla** [comment]
This is probably a launch blocker for python microgenerator.

**Comment by hkdevandla** [comment]
Marking this as a bug since it breaks auto-synth.

**Comment by software-dov** [comment]
Fixed by #438
