### ISSUE TITLE
Move generated unit tests to unit/gapic directory

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#454]
I noticed we didn't actually lint the generated code in the monolith, and I don't think it's necessary for the microgenerator either. (See [.flake8](https://github.com/googleapis/synthtool/blob/f06a850db98490bf90c6a476d3f4c6c7cdfb1e5e/synthtool/gcp/templates/python_library/.flake8#L19-L32))

Could we move the generated tests to `tests/unit/gapic` so flake8 will ignore it with the rule `**/gapic/**`?

We can't blanket ignore `**/unit/**` because hybrid libraries (e.g. Pub/Sub) may have hand written unit tests.

Related to #425, #323

**Comment by software-dov** [comment]
Seems reasonable

**Comment by software-dov** [comment]
Fixed by #456
