### ISSUE TITLE
How to specify a different path for generated outputs (firestore)

### ISSUE THREAD

**Issue by crwilcox** [googleapis/gapic-generator-python#471]
Firestore APIs are at //google/firestore but we want them to be namespaced as google.cloud.firestore. 

I have tried changing the package name in py_gapic_library in build.bazel, but outputs are still to google/firestore.

How should I specify to change the location?

```

py_gapic_library(
    name = "firestore_py_gapic",
    src = ":firestore_proto_with_info",
    gapic_yaml = "firestore_gapic.yaml",
    package = "google.cloud.firestore.v1",
    service_yaml = "//google/firestore:firestore_v1.yaml",
    deps = [
        ":firestore_py_grpc",
        ":firestore_py_proto",
    ],
)
```

**Comment by crwilcox** [comment]
The client assumes we want `google.firestore` but we lay things out as `google.cloud.firestore`

**Comment by arithmetic1728** [comment]
The solution is to add a `opt_args=["python-gapic-namespace=google.cloud"]` rule to `py_gapic_library`. The `python-gapic-namespace` value can be calculated by first replacing `google` with `google.cloud` and then removing the api name, so for `google.firestore`, it's `google.cloud`; for `google.devtools.cloudbuild`, it's `google.cloud.devtools`. I tried with `cloudbuild` api, it works for me. It fixes both directory path and namespace.

```
load(
    "@com_google_googleapis_imports//:imports.bzl",
    py_gapic_assembly_pkg = "py_gapic_assembly_pkg2",
    py_gapic_library = "py_gapic_library2",
)

py_gapic_library(
    name = "cloudbuild_py_gapic",
    srcs = [":cloudbuild_proto"],
    opt_args=["python-gapic-namespace=google.cloud.devtools"],    <=========== here
    grpc_service_config = "cloudbuild_grpc_service_config.json",
)

py_gapic_assembly_pkg(
    name = "devtools-cloudbuild-v1-py",
    deps = [
        ":cloudbuild_py_gapic",
    ],
)
```
