### ISSUE TITLE
extra pair of backticks breaks generated doc

### ISSUE THREAD

**Issue by dizcology** [googleapis/gapic-generator-python#479]
Example: https://github.com/googleapis/python-documentai/blob/master/google/cloud/documentai_v1beta2/services/document_understanding_service/client.py#L260

it has:

```
:class:``~.document_understanding.BatchProcessDocumentsResponse``
```

The library reference doc generated with sphinx fails to create cross reference link: https://googleapis.dev/python/documentai/latest/documentai_v1beta2/services.html#google.cloud.documentai_v1beta2.DocumentUnderstandingServiceClient.batch_process_documents

**Comment by arithmetic1728** [comment]
any updates as we are out of slo

**Comment by software-dov** [comment]
Seems to be fixed in current.
