### ISSUE TITLE
Add service and version to fixup script

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#488]
One library can have multiple keyword scripts. This may be because it has multiple API versions (v1, v2) or different APIs (firestore and firestore admin).

https://github.com/googleapis/gapic-generator-python/blob/161e48613934058780f82e15f71cbc9f574fdf65/gapic/templates/scripts/fixup_keywords.py.j2

**Comment by software-dov** [comment]
Fixed by #490
