### ISSUE TITLE
bazel: py_gapic_library rule should support specifying grpc_service_config

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator-python#522]
The generator can consume the retry/timeout config from the grpc_service_config file by passing the file through a protoc option. This should be reflected on the surface of the `py_gapic_library` rule as a `grpc_service_config` attribute. This is necessary for migration of generation targets to the microgenerator as a majority of APIs have already been moved to this config. 

Examples of other languages that have implemented this attribute in their rules include:
- https://github.com/googleapis/gapic-generator-go/blob/master/rules_go_gapic/go_gapic.bzl#L88-L91
- https://github.com/googleapis/gapic-generator-typescript/blob/master/rules_typescript_gapic/typescript_gapic.bzl#L41-L42

**Comment by busunkim96** [comment]
Closed by #526. Microgenerated Python libraries are now using the service config.
