### ISSUE TITLE
Microgenerator creates PubSub client with some incompatibilities

### ISSUE THREAD

**Issue by plamut** [googleapis/gapic-generator-python#530]
**Disclaimer:** This might be invalid and the "bugs" might actually be features. I would like to determine whether these changes were actually made on purpose or not.

---

When migrating the Python PubSub library to microgenerator, some additional breaking changes were encountered that are not just the _"methods now expect `request` as the first arg"_:

 - There are not IAM-related methods anymore, namely `get_iam_policy()`, `set_iam_policy()`, `test_iam_permission()`.
 - `subscriber.create_subscription()` does not anymore support arguments such as `retain_ack_messages`, `message_retention_duration`, `expiration_policy`, and `dead_letter_policy`.
 - The `project_path()` method does not exist in neither client (subscriber, publisher)
 - Publisher client constructor does not support the `client_config` parameter anymore (for customizing timeouts per methods/method groups). Has this been replaced by the retry policy?
- The result of `publisher.list_topic_subscriptions()` is not iterable. Unlike some other `list_*()`methods it directly returns `ListTopicSubscriptionsResponse` instead of something like `ListTopicSubscriptionsPager`.
- (nit) Creating a topic, subscription, etc. expects a `name` argument (resource path as a string), while the same argument is named `topic`/ `subscription`, etc. deleting/updating a resource. Is this intended?

I would primarily like to know whether these are legitimate issues with the generator, or is this something that has been changed on purpose and the library needs to be adjusted. Thanks!

**Comment by busunkim96** [comment]
@plamut, thanks for the detailed writeup! 

> There are not IAM-related methods anymore, namely `get_iam_policy()`, `set_iam_policy()`, `test_iam_permission()`.

Opened #536 to discuss further.

> `subscriber.create_subscription()` does not anymore support arguments such as `retain_ack_messages`, `message_retention_duration`, `expiration_policy`, and `dead_letter_policy`.

The flattened params (available as kwargs on the method) are determined by [`google.api.method_signature`](
https://github.com/googleapis/googleapis/blob/bb46f87724ddd2fd1ce9f9dcb71f147427775592/google/pubsub/v1/pubsub.proto#L404-L411). For this method they are `name`, `topic`, `push_config`, and `ack_deadline_seconds`.

To access other fields you are expected to construct a request (Subscription) object.

```py
subscription = Subscription(...)
create_subscription(request=subscription)
```

> The `project_path()` method does not exist in neither client (subscriber, publisher)

This is expected. The resource helper methods were specified manually in the GAPIC yaml for the monolith. In the microgenerator, it is inferred from messages. See https://github.com/googleapis/gapic-generator-python/pull/253 for the implementation. 

> Publisher client constructor does not support the `client_config` parameter anymore (for customizing timeouts per methods/method groups). Has this been replaced by the retry policy?

@software-dov could you take this one?


> The result of `publisher.list_topic_subscriptions()` is not iterable. Unlike some other `list_*()`methods it directly returns `ListTopicSubscriptionsResponse` instead of something like `ListTopicSubscriptionsPager`.

It seems like there might be another bug with the pagination heuristic. Could you spin this out into a separate issue? 


> (nit) Creating a topic, subscription, etc. expects a `name` argument (resource path as a string), while the same argument is named `topic`/ `subscription`, etc. deleting/updating a resource. Is this intended?

Yes, I think this is the generator just being faithful to the naming in the protos. Create methods accept a `name` while methods that *use* a topic or subscription refer to it as `topic`/`subscription`. [CreateTopic](https://github.com/googleapis/googleapis/blob/bb46f87724ddd2fd1ce9f9dcb71f147427775592/google/pubsub/v1/pubsub.proto#L48-L54 ) vs [UpdateTopic](https://github.com/googleapis/googleapis/blob/bb46f87724ddd2fd1ce9f9dcb71f147427775592/google/pubsub/v1/pubsub.proto#L58-L63)

**Comment by plamut** [comment]
@busunkim96 Thanks for the quick and thorough answer!

Most of the things turned out to not be bugs, which is great, and I'll make the necessary adjustments in the new PubSub client. Also created #537 to discuss the iterability of `publisher.list_topic_subscriptions()` results.

**Comment by software-dov** [comment]
Just confirmed that the ListTopicSubscriptions is properly paginated on the most current generator.

**Comment by busunkim96** [comment]
@software-dov Woo that's good to hear.  

Is the right way to set retry/timeout via the method-level [`retry` and `timeout`args](https://github.com/googleapis/python-texttospeech/blob/887d8d501ce9255fee44170b5fc40ebfb1ea953d/google/cloud/texttospeech_v1/services/text_to_speech/client.py#L288-L289)?

> Publisher client constructor does not support the `client_config` parameter anymore (for customizing timeouts per methods/method groups). Has this been replaced by the retry policy?

**Comment by software-dov** [comment]
Closing issue as specifics have their own issues filed.
