### ISSUE TITLE
Add alternative to `reroute_to_grpc_interface`

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#536]
Pub/Sub and KMS use the [`reroute_to_grpc_interface`](https://github.com/googleapis/googleapis/search?q=reroute_to_grpc_interface&unscoped_q=reroute_to_grpc_interface) option in the GAPIC yaml to add additional IAM methods with the monolithic generator. This adds the methods `get_iam_policy()`, `set_iam_policy()`, `test_iam_permission()`.  There is no equivalent in the microgenerator.

IAM v1 is a full-fledged API and can be generated with the existing protos/configs [here](https://github.com/googleapis/googleapis/tree/master/google/iam/v1).

Options:

* Publish the google/iam/v1* client somewhere. Possible locations: [grpc-google-iam-v1](https://pypi.org/project/grpc-google-iam-v1/), [google-cloud-iam](https://github.com/googleapis/python-iam),  `google-api-core`, some new package.
* Add an option to the generator to add IAM methods.

Thoughts?

Here is what NodeJS did for reference: https://github.com/googleapis/gax-nodejs/pull/762 and https://github.com/googleapis/gapic-generator-typescript/pull/375

CC @plamut @software-dov

**Comment by plamut** [comment]
I'm fine with either option, whatever makes the future maintenance easier. Or, if one option is significantly faster to implement than the other, let's go with it and possibly make a switch to the other option later.

**Background:** Having the IAM methods in PubSub client is a prerequisite for the upcoming major release. We currently put all other PRs on hold to not interfere with these changes, thus we would like to make the major release in the near future, if possible.

**Comment by software-dov** [comment]
My kneejerk reaction is to publish google/iam/v1*. Do we have a good estimate on how much initial/recurring effort that would involve?

**Comment by busunkim96** [comment]
I did some investigation to figure out why this is only used for two APIs. `reroute_to_grpc_interface` seems to be a hack (see internal thread [1](https://groups.google.com/a/google.com/forum/#!msg/veneer-toolkit/ddJqCU2FQVs/51RlvbtWFQAJ) and [2](https://groups.google.com/a/google.com/d/msg/cloud-pubsub-eng/auIqa3Axdsg/aWQFq1ceBwAJ) ).  The recommended way to add IAM is as a _mix-in API_. This is what the [vast majority of APIs do](https://github.com/googleapis/googleapis/search?q=rpc+setiampolicy&unscoped_q=rpc+setiampolicy). The IAM methods are copied [into the service protos](https://github.com/googleapis/googleapis/blob/b5e9b0b09cc15c263f07da92fa64db31b2e4dd07/google/cloud/datacatalog/v1beta1/policytagmanager.proto#L130-L166) and the generator happily produces those methods.

If we publish a separate client, users have to instantiate a separate IAM client for *only* Pub/Sub and KMS, which doesn't seem like a good experience.

I *don't think* it will be too terrible to do this in the generator (the 3 methods don't seem to change from API to API). I'm going to take a stab at a PR, but if it starts to get out of hand we can do something more similar to what Node did.

**Threads from other microgenerators:**
* https://github.com/googleapis/gapic-generator-typescript/pull/375 and [design doc](https://docs.google.com/document/d/1UOORCBdcG32R_FqaiCuuQ8KF8AQTpyYTyui6a7EFeHc/edit#heading=h.jyjlyheps42e)
* https://github.com/googleapis/gapic-generator-ruby/pull/424

**Comment by software-dov** [comment]
Spitballing: would copying the requisite messages/rpcs to a separate proto file and then importing that in KMS/PubSub/et al. be sufficient?

**Comment by busunkim96** [comment]
@software-dov The main issue seems to be that the IAM calls need to go to `iam.googleapis.com` instead of `pubsub.googleapis.com` or `kms.googleapis.com`, since these APIs don't know what to do with these method calls. Making that happen in the proto files would be the cleanest solution. (I assumed it wasn't an option since Ruby and Node seem to have changed their generators to accommodate this.)

[KMS transport](https://github.com/googleapis/python-kms/blob/8abd7cf3529fa12169d09cebba41fc0ee2fb6f6a/google/cloud/kms_v1/gapic/transports/key_management_service_grpc_transport.py#L469) vs [container analysis](https://github.com/googleapis/python-containeranalysis/blob/bc56231c33ae37f5713ac14cd72f457789f097ee/google/cloud/devtools/containeranalysis_v1/gapic/transports/container_analysis_grpc_transport.py#L133)
