### ISSUE TITLE
The result of publisher.list_topic_subscriptions() should be iterable

### ISSUE THREAD

**Issue by plamut** [googleapis/gapic-generator-python#537]
(Spinning off from #530)

The result of `publisher.list_topic_subscriptions()` is not iterable. Unlike some other `list_*()` methods it directly returns `ListTopicSubscriptionsResponse` instead of something like `ListTopicSubscriptionsPager`. Developers thus need to iterate over `response.subscriptions`, which is somewhat less elegant and inconsistent with how results of the other `list_*()` methods can be handled.

**Comment by software-dov** [comment]
Unable to reproduce with most current generator: list_topic_subscriptions is properly paginated in the generated surface. Duplicate of #516 ; closing as fixed.
