### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator-python#538]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by software-dov** [comment]
Is there a procedure guide for enabling these protections?
The repo already requires at least one approval, but I don't know how to add the other constraints.

**Comment by JustinBeckwith** [comment]
Sure!  There are two ways to do this stuff.  One - you can work with @busunkim96 to get the settings configured here:
https://github.com/googleapis/repo-automation-bots/blob/master/packages/sync-repo-settings/src/required-checks.json

Or, you can saunter into the the `settings` section of the repo, and enable the manually.

**Comment by busunkim96** [comment]
@software-dov I went through and marked most of the existing circleci checks as "required". You can add/remove checks [here](https://github.com/googleapis/gapic-generator-python/settings/branch_protection_rules/1711128).

**Comment by busunkim96** [comment]
Closing since the requirement (2+ checks) is satisfied.
