### ISSUE TITLE
api_core.path_template import not present when needed

### ISSUE THREAD

**Issue by software-dov** [googleapis/gapic-generator-python#565]
See https://github.com/googleapis/python-firestore/pull/141

**Comment by tseaver** [comment]
@busunkim96 remembered:

> I remember why this happened now. Firestore lost its path methods when the protos were moved over to proto annotations.  I added synth replaces to add the methods (https://github.com/googleapis/python-firestore/blob/master/synth.py#L55) but not the imports.

**Comment by busunkim96** [comment]
Closing since this was the result of an incomplete synth replace rather than a bug in the generator.
