### ISSUE TITLE
Allow custom ClientInfo

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#566]
Clients are currently always using the default ClientInfo. https://github.com/googleapis/gapic-generator-python/blob/1d08e60cea4c5b3fa2555a4952161b0115d686f2/gapic/ads-templates/%25namespace/%25name/%25version/%25sub/services/%25service/transports/base.py.j2#L95

Allow `ClientInfo` to be passed as a kwarg to the constructor and use it when provided.

https://github.com/googleapis/python-kms/issues/37

**Comment by software-dov** [comment]
Fixed by #573
