### ISSUE TITLE
Feature Request: allow clients to act as context manager and add close() method to cleanup resources

### ISSUE THREAD

**Issue by tswast** [googleapis/gapic-generator-python#575]
Since a `transport` object may be passed into a client constructor, the client does not close that transport in when the client object is deleted. This results in leaking socket resources in programs that create client objects dynamically.

**Proposed design:**

Add the following two ways to explicitly clean-up sockets owned by the client: (1, preferred) allow clients to act as a context manager and (2) a close() method.

1.  Context manager

    Allow all client objects to be used as a context manager. Call close() on the client in the __exit__ method to clean up sockets owned by the client.

    In code samples with short-lived clients, this is the cleanup method we should recommend.

Example:

```python
from google.cloud import bigquery_datatransfer_v1

with bigquery_datatransfer_v1.DataTransferServiceClient() as client:
    print(client.get_transfer_run('some run id').state)
```

2.  `close()` method

    Add a `close()` method to all client objects. When called, clean up sockets owned by the client, including the transport channel.

    Example:

```python
from google.cloud import bigquery_datatransfer_v1

client = bigquery_datatransfer_v1.DataTransferServiceClient()
print(client.get_transfer_run('some run id').state)
client.close()  # clean up any open sockets
```

**References:**

* go/closable-clients-python (Google internal)
* https://github.com/googleapis/google-cloud-python/issues/9457
* https://github.com/googleapis/google-cloud-python/pull/9894
* https://github.com/googleapis/python-kms/issues/2

**Comment by tswast** [comment]
Note: this issue is even more important in the microgenerator, as the `transport` property now appears to be private.

**Comment by software-dov** [comment]
This is made slightly more complicated because of ownership. Because it's an injected parameter, we can't be sure that the client has the sole reference to the transport; we may wind up closing a transport that other clients are still using. This kind of a corner case, though, and it can probably be ameliorated with documentation and warnings to USE AT YOUR OWN RISK.
I agree, in principle, that having both context management and an explicit `close` method` are the right choice, but I'd like to spend a little more time mulling details.

**Comment by tswast** [comment]
To cross-link a bit, this / change in `transport` is affecting the BigQuery client library. It's a case where the BigQuery client library has ownership of a BigQuery Storage client library that it creates, so we must close it when we're done to avoid leaking system resources.

We're currently working around this issue in https://github.com/googleapis/python-bigquery/pull/278 by calling

```
self._bqstorage_client._transport.grpc_channel.close()
```

when done with the BigQuery Storage client.

**Comment by software-dov** [comment]
Do we need to bump the priority of this feature?

**Comment by tseaver** [comment]
Can we just add `close`, and then document using `contextlib.closing` as the way to do the cleanup automatically, including a note on the problematic passed-in-transport case?
