### ISSUE TITLE
Generate common resource path helpers via google/cloud/common_resources.proto

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#586]
https://github.com/googleapis/googleapis/blob/master/google/cloud/common_resources.proto

I was visiting the Node chat and learned of the existence of the above file. Can we use it somehow to get more resource helpers methods into all the libraries? (the two with projects would be most useful I think)

* "projects/{project}"
* "organizations/{organization}"
* "folders/{folder}"
* "billingAccounts/{billing_account}"
* "projects/{project}/locations/{location}"

**Comment by software-dov** [comment]
This should be straightforward and easy. There are a couple of potential gotchas:
1) The path definitions in `common_resources.proto` don't have messages associated. This will require a little bit of rework in the generator logic and template.
2) The _correct_ thing to do would be to have `common_resources.proto` imported and then to use the descriptors to generate paths. I don't think we can do that by the time the generator plugin runs, so we'll need to just hack it in.
3) There's a potential for name conflicts. One way to deal with this is to ignore it until a problem arises; another is to have a common disambiguation string, e.g. `def common_project_path` and `def parse_common_project_path`. Neither option seems great, but I'm leaning towards the second.

What do other people think? @vam-google @busunkim96
