### ISSUE TITLE
enum classes are missing docstrings

### ISSUE THREAD

**Issue by tswast** [googleapis/gapic-generator-python#625]
https://github.com/googleapis/python-bigquery/pull/278#discussion_r497502192

Ideally, there would be a docstring for each enum showing all the available values. This is a regression from the monolith generator.

**Comment by software-dov** [comment]
Just curious, but is a docstring necessary for autogenerated documentation that's derived from the docstrings? Because it's easy to just...look at the values.

**Comment by tswast** [comment]
Docstring isn't 100% necessary, but it would be good to show the values in the docs themselve. Having to click "view source" is a regression.

**Comment by busunkim96** [comment]
Looks like adding `undoc-members` to `types.rst` fixes this. Change pending in #714.

![image](https://user-images.githubusercontent.com/8822365/102832003-669d0580-43aa-11eb-9536-ef3f62460676.png)
