### ISSUE TITLE
docs: not clear that generated types have serialize / deserialize methods

### ISSUE THREAD

**Issue by tswast** [googleapis/gapic-generator-python#685]
I had a customer that was pickling protobuf objects because they didn't know they could serialize / deserialize the protocol buffer objects. (internal issue 171748167)

If you browse the documentation at https://googleapis.dev/python/bigquerystorage/latest/bigquery_storage_v1/types.html there is no indication that this is possible.

**Suggestion 1**

Show that these objects are inherited from proto-plus message objects and use intersphinx to ensure they get a clickable link to the Message reference docs https://proto-plus-python.readthedocs.io/en/latest/reference/message.html#proto.message.Message

**Suggestion 2**

Add `:show-inheritance:` and `:inherited-members:` to the [types.rst](https://github.com/googleapis/python-bigquery-storage/blob/master/docs/bigquery_storage_v1/types.rst) file.

**Comment by software-dov** [comment]
What's the consensus on whether this is fixed by #680 ?

**Comment by tswast** [comment]
I haven't cut a release yet since https://github.com/googleapis/python-bigquery-storage/pull/91 and https://github.com/googleapis/python-bigquery-storage/pull/86 so I'm not sure if it's enough. Should be an improvement at least, though.

**Comment by software-dov** [comment]
Moving to close since the change has been made in the generator.

**Comment by tswast** [comment]
Thanks, just cut a release. https://googleapis.dev/python/bigquerystorage/latest/bigquery_storage_v1/types.html looks pretty good to me. Hopefully customers click on that base class link.
