### ISSUE TITLE
Compute library appears to assign large numbers for enums

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#727]
I noticed this while generating the Compute API via DIREGAPIC. Is it a side effect of the number of resources in the API? 

Example enum:

```py
    class Continent(proto.Enum):
        r"""[Output Only] Continent for this location, which can take one of the
        following values:

        -  AFRICA
        -  ASIA_PAC
        -  EUROPE
        -  NORTH_AMERICA
        -  SOUTH_AMERICA
        """
        UNDEFINED_CONTINENT = 0
        AFRICA = 49008250
        ASIA_PAC = 119782269
        C_AFRICA = 71993846
        C_ASIA_PAC = 197232633
        C_EUROPE = 200369438
        C_NORTH_AMERICA = 7261592
        C_SOUTH_AMERICA = 128714336
        EUROPE = 177383842
        NORTH_AMERICA = 179580052
        SOUTH_AMERICA = 32597340

```

I looked at AutoML for comparison and the enum values usually start from 0/1.

https://github.com/googleapis/python-automl/blob/4c910d37dd882d8d4248c1b3716213e9aacbf5df/google/cloud/automl_v1/types/data_items.py#L96-L107

```py
    class DocumentDimensionUnit(proto.Enum):
        r"""Unit of the document dimension."""
        DOCUMENT_DIMENSION_UNIT_UNSPECIFIED = 0
        INCH = 1
        CENTIMETER = 2
        POINT = 3
```

CC @yon-mg @vam-google

**Comment by vam-google** [comment]
This is expected. The same thing happens for the numbers in the fields in every message. In short, those numbers are hashes of the field names. We need it to keep field numbers stable when regenerated from discovery documents with potential updates in them. If we assign the numbers sequentially and there is a field inserted in an existing message (discovery just puts fields in alphabetical order) it will shift the numbers of all the fields after the new field in a message resulting into a breaking change.

Do big numbers cause a problem in python client?

**Comment by busunkim96** [comment]
It doesn't cause a problem, just thought it was odd and wanted to follow up. Thanks for the quick response!

**Comment by software-dov** [comment]
So you're saying that with carefully chosen variant names, I could cause a collision? :)

**Comment by vam-google** [comment]
@software-dov Yes, you can =) Thought we haven't seen any collisions yet on real APIs. The collision will still be resolved using open addressing method, though.
