### ISSUE TITLE
Routing headers are not passed to the operations client

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#732]
See internal issue 173104871 for more details.

Some APIs require routing headers (location info in`x-goog-request-params`) for successful requests. https://google.aip.dev/client-libraries/4222

https://github.com/googleapis/gapic-generator-python/blob/e5b7648e5f3cf03e6a7b535c8e96b22705a570ba/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/client.py.j2#L412-L435

These headers are added to normal requests to the API but are missing in calls to the Operations API. This results in requests failing with permission denied errors.

https://github.com/googleapis/gapic-generator-python/blob/e5b7648e5f3cf03e6a7b535c8e96b22705a570ba/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/client.py.j2#L436-L444

A fix will require:

1.  new version of `google-api-core` with an operations client that accepts and uses gRPC metadata
2.  An update to the generator templates.

**Comment by noahdietz** [comment]
FWIW the Go GAPICs use an LRO GAPIC under the hood. The LRO GAPIC is made using the google/longrunning/operations.proto which have `google.api.http` annotations on the RPCs that declare the `name` field as a request param [here](https://github.com/googleapis/googleapis/blob/bbb3fc423941ba7356f8217c3c74589de0b47885/google/longrunning/operations.proto#L69). So then, per https://google.aip.dev/client-libraries/4222, the Go gapic generator makes sure to include the code that injects the `name` field of the Operation as `x-goog-request-params`. Thus, all LRO RPCs have the `name=...` request param. This was the missing header necessary in the internal bug, but why tests with the Go gapic succeeded when Python's failed.

**Comment by alexander-fenster** [comment]
I understand why it may require `name` field, but why `location`? Would it be enough to just pass the `name` request header for LRO?

**Comment by noahdietz** [comment]
I had the same thought last night. I think you are right, @alexander-fenster, passing the value of the `Operation.name` should be sufficient. That is what the Go GAPICs do and it works properly.

I think `location` came up in discussion because the routing rules were parsing out the `Location` parent of the `Operation.name`.

This could be straight forward as passing the `Operation.name` to `x-goog-request-params` on every request.

cc: @viacheslav-rostovtsev

**Comment by alexander-fenster** [comment]
OK, thank you @noahdietz – then for TypeScript it's just a quick fix to the operations client that is in google-gax (it was originally a generated GAPIC but never updated, for some reason it does not pass `x-goog-request-params`, maybe it was frozen before that became a thing).

**Comment by busunkim96** [comment]
I think I can just make this fix in Python's gax then - `google-api-core`. Thanks for the clarification @noahdietz @alexander-fenster!  🙏

**Comment by busunkim96** [comment]
Opened https://github.com/googleapis/python-api-core/pull/133
