### ISSUE TITLE
Turn REST response exceptions into `GoogleAPICallError`

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#769]
Currently the REST transport uses `response.raise_for_status()` and returns the exception object from `requests`.

https://github.com/googleapis/gapic-generator-python/blob/cc55a182b878d78f92aba259c067d47ab1d01e5b/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/transports/rest.py.j2#L206

For consistency with existing libraries the response should be converted into a `GoogleAPICallError`.

https://github.com/googleapis/python-api-core/blob/db48ea3f8f69cd5039cdc2e35a0a3604d731bc70/google/api_core/exceptions.py#L399

**Comment by yon-mg** [comment]
Addressed in upcoming pr.
