### ISSUE TITLE
Addition of `policy` and `options` to reserved names in #824 results in breaking changes to stable libraries

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#835]
These APIs have field renames resulting from this #824 which expanded the `RESERVED_NAMES` list. Some of them are GA, and even for beta APIs I'd prefer not to take changes that looks spurious from the user's perspective. 

https://github.com/googleapis/python-artifact-registry/pull/12
https://github.com/googleapis/python-cloudbuild/pull/81
https://github.com/googleapis/python-iot/pull/87
https://github.com/googleapis/python-functions/pull/45
https://github.com/googleapis/python-securitycenter/pull/120
https://github.com/googleapis/python-bigquery-connection/pull/57
https://github.com/googleapis/python-containeranalysis/pull/112
https://github.com/googleapis/python-bigtable/pull/280
https://github.com/googleapis/python-tasks/pull/85
https://github.com/googleapis/python-policy-troubleshooter/pull/8
https://github.com/googleapis/python-asset/pull/171
https://github.com/googleapis/python-org-policy/pull/32
https://github.com/googleapis/python-binary-authorization/pull/18
https://github.com/googleapis/python-spanner/pull/303
https://github.com/googleapis/python-secret-manager/pull/100/
https://github.com/googleapis/python-firestore/pull/336
https://github.com/googleapis/python-billing/pull/55
https://github.com/googleapis/python-datacatalog/pull/143

`policy` and `options` are the two that show up in these APIs.

From looking at the regen, it doesn't look like these need to be added to the reserved names list? https://github.com/googleapis/gapic-generator-python/commit/f5e9f367ec6a72b4272f559a93f6fbb3d7e54b8b seems to result in the imports being renamed to not conflict. I see `from google.iam.v1 import policy_pb2 as giv_policy` ([example](https://github.com/googleapis/python-bigtable/pull/280/files#diff-aa015723229f8d7fd386f79dab53254d30ea8e10c880a6d12627f4d60ec3441fR42)) instead of `from google.iam.v1 import policy_pb2 as policy`.

Can `policy` and `options` be removed from the list? @software-dov

**Comment by software-dov** [comment]
Options cannot, policy may be. @parthea can chime in for context, I think he's working with the APIs that require these names.

**Comment by parthea** [comment]
The issue I encountered was with keyword `auth` in API `servicecontrol` `v1`. We could certainly limit the impact of this change if we only add `auth` as a reserved name.

Prior to generator version 0.43.2 there was a conflict with `auth`
```
from google import auth
from google.api import auth_pb2 as auth  # type: ignore
```

With the fix in version 0.43.2
```
from google import auth
from google.api import auth_pb2 as ga_auth  # type: ignore
```

You can see the change here:
https://github.com/googleapis/googleapis-gen/commit/107ed1217b5e87048263f52cd3911d5f851aca7e#diff-c8fa0e83f42f4ec28657fd35abc265e70911e8487762f7ae1891e4747ba791b9L28

**Comment by busunkim96** [comment]
Given what @parthea shared, is it possible to back out the change?

Or can we tweak the raw imports in the templates to use references that are less likely to conflict?

```py
from google import auth

credentials, _ = auth.default(scopes=self._scopes, quota_project_id=quota_project_id)
```

```py
import google.auth

credentials, _ = google.auth.default(scopes=self._scopes, quota_project_id=quota_project_id)
```

**Comment by parthea** [comment]
@software-dov, PTAL

**Comment by tswast** [comment]
I think this is breaking generation of the datacatalog library https://github.com/googleapis/python-datacatalog/pull/143#issuecomment-823470174

**Comment by software-dov** [comment]
Do we have a sense of how time critical this issue is, or a required timeline?

**Comment by busunkim96** [comment]
@software-dov I'm currently blocking generator updates on the repos listed. So any features since that change (GAPIC metadata and self-signed JWT) will not land in those repos for the time being.

I could technically add synth replaces to avoid the breaking change, but would rather not do so for 10+ repos since it is error prone.
