### ISSUE TITLE
Generated tests for `python-<API>` are not complete

### ISSUE THREAD

**Issue by Shabirmean** [googleapis/gapic-generator-python#837]
The re-generated tests in some PRs are in-complete. This is related to the keyword `policy` being added to reserved names list, thus requiring a rename of the use of `policy` in the library to something like `policy_`

[PR#50 of grafeas](https://github.com/googleapis/python-grafeas/pull/50) : [Failing tests](https://source.cloud.google.com/results/invocations/8aab1632-0166-4950-a474-aa7f0f3d8cc7/targets/github%2Fpython-grafeas/tests;group=tests.unit.gapic.grafeas_v1.test_grafeas;test=test_grafeas_transport_channel_mtls_with_client_cert_source%5BGrafeasGrpcTransport%5D;row=1)
[PR#51 of grafeas](https://github.com/googleapis/python-grafeas/pull/51) : [Failing tests](https://source.cloud.google.com/results/invocations/23e1d54b-0cd5-44fa-a422-29c8f5f25d66/targets/github%2Fpython-grafeas/tests;group=tests.unit.gapic.grafeas_v1.test_grafeas;test=test_grafeas_grpc_transport_channel_mtls_with_client_cert_source;row=1)
[PR#18 of python-binary-authorization](https://github.com/googleapis/python-binary-authorization/pull/18) : [Failing tests](https://source.cloud.google.com/results/invocations/35688111-edd1-47e0-abfe-539f8b57cb67/targets/github%2Fpython-binary-authorization/tests)
[PR#112 of python-containeranalysis](https://github.com/googleapis/python-containeranalysis/pull/112) : [Failing tests](https://source.cloud.google.com/results/invocations/e5c7d87e-a89c-4694-8d9d-e7c22eccf4c2/targets/github%2Fpython-containeranalysis/tests)
[PR#12 of python-artifact-registry](https://github.com/googleapis/python-artifact-registry/pull/12) : [Failing tests](https://source.cloud.google.com/results/invocations/0e50b061-3741-4c7c-922a-4a31d9a28186/targets/github%2Fpython-artifact-registry/tests)

Also related: https://github.com/googleapis/gapic-generator-python/issues/835

**Comment by software-dov** [comment]
@Shabirmean how serious would you say this issue is? Does it require immediate attention, or does it just block gapic regeneration?

**Comment by Shabirmean** [comment]
@software-dov - I'd share the same as shared by @busunkim96 [here](https://github.com/googleapis/gapic-generator-python/issues/835#issuecomment-824342287). 

For the `python-cloudbuild`, `python-artifact-registry` and `python-containeranalysis` it seems like it's just the gapic regeneration. However for `python-grafeas` there are features that are not merged in due to this blocker.

**Comment by software-dov** [comment]
Closing due to test coverage now being complete. Can reopen the issue if it resurfaces.
