### ISSUE TITLE
bidi should use transport client_info

### ISSUE THREAD

**Issue by jameslynnwu** [googleapis/gapic-generator-python#911]
#### Environment details

  - Programming language: Python
  - OS: Linux
  - Language runtime version: 3.6.13
  - Package version: 

#### Steps to reproduce
Using https://github.com/googleapis/python-logging/tree/master/google/cloud/logging_v2

```
client_info = google.api_core.gapic_v1.client_info.ClientInfo(
    user_agent="User agent string")
transport = LoggingServiceV2GrpcTransport(
      client_info=client_info)
# Didn't include custom user agent specified in my transport client_info.
self.tail_stub = bidi.BidiRpc(transport.tail_log_entries)
```

Using the same client_info, I added additional metadata to bidi.BidiRpc
```
# Worked
method = transport.tail_log_entries
# method type <grpc._interceptor._StreamStreamMultiCallable object at 0x7fb31280a080>
self.tail_stub = bidi.BidiRpc(method, metadata=[client_info.to_grpc_metadata()])
```
I expect that the bidi library should use the client_info that the transport object is set up with.

I dug in a little deeper and saw that client_info is attached via `_wrapped_methods`, which bidi does not use, so I attempted to pass in the wrapped method, instead of just transport.tail_log_entries, but that didn't work.
```
# Didn't work either
method = transport._wrapped_methods[transport.tail_log_entries]
# method type <google.api_core.gapic_v1.method._GapicCallable object at 0x7fb30df45f60>
self.tail_stub = bidi.BidiRpc(method)
```

**Comment by busunkim96** [comment]
Since this change will need to be made in google-api-core, let's track the issue there. https://github.com/googleapis/python-api-core/issues/202
