### ISSUE TITLE
403 permission denied errors in some libraries with `always_use_jwt_access` = True

### ISSUE THREAD

**Issue by busunkim96** [googleapis/gapic-generator-python#929]
@parthea noticed some library system and sample tests failing in PRs adding `always_use_jwt_access`  (see #920)

There are three slightly different error messages:

---

1.  `google.api_core.exceptions.PermissionDenied: 403 Provided scope(s) are not authorized`

    - https://github.com/googleapis/python-asset/pull/211 - Strangely, only [**one sample**](https://github.com/googleapis/python-asset/blob/master/samples/snippets/quickstart_analyzeiampolicylongrunning.py)  fails. The other 11 sample tests passed.

    - https://github.com/googleapis/python-speech/pull/184 

---
2. `google.api_core.exceptions.PermissionDenied: 403 The caller does not have permission`

    - https://github.com/googleapis/python-videointelligence/pull/168 

---
3. `google.api_core.exceptions.PermissionDenied: 403 User does not have sufficient permissions for this property. To learn more about Property ID, see https://developers.google.com/analytics/devguides/reporting/data/v1/property-id.`

    - https://github.com/googleapis/python-analytics-data/pull/92 

Sample tests in many other repositories _did_ pass, and I do not see an obvious difference between these APIs and the ones above.

- https://github.com/googleapis/python-kms/pull/129
- https://github.com/googleapis/python-secret-manager/pull/137
- https://github.com/googleapis/python-automl/pull/175

**Comment by parthea** [comment]
Raising priority to P1 as we're [blocking releases](https://github.com/googleapis/python-asset/pull/211#issuecomment-867893283) due to this bug.

**Comment by arithmetic1728** [comment]
working on it now

**Comment by parthea** [comment]
Thanks so much!

**Comment by arithmetic1728** [comment]
Created a PR to fix this: https://github.com/googleapis/gapic-generator-python/pull/935
