### ISSUE TITLE
gapic-generator-python fails to complete with a sufficiently large protobuf tree

### ISSUE THREAD

**Issue by tmc** [googleapis/gapic-generator-python#950]
This generator fails when there is a type reference to a very large protobuf type tree. (For example, the types described at https://github.com/google/fhir/tree/master/proto/google/fhir/proto ).

Initial debugging appears to show that MessageType.with_context is where the majority of the time is spent.

**Comment by tmc** [comment]
@software-dov Curious if you have anything to share regarding this.

**Comment by tmc** [comment]
@software-dov I experimented and by moving away from FrozenSet and by ensuring the same set() instance is threaded through the service/message/field tree the generation time+memory goes down from non-terminating and consuming 32G to finishing within 2 minutes.

**Comment by vam-google** [comment]
Waiting for https://github.com/googleapis/gapic-generator-python/pull/1125 to be merged. @tmc can you please follow up on it? Thanks!

**Comment by tmc** [comment]
@vam-google I think that PR needs review.

**Comment by vchudnov-g** [comment]
It seems like this was fixed by #1125 . If not, please file a new issue so we can follow up. Thanks!
